<template>
     <!--footer-->
    <div class="footer">
        <div class="container">
            <div class="footer-top">
                <div class="col-md-6 top-footer animated wow fadeInLeft" data-wow-delay=".5s">
                    <h3>Follow Us On</h3>
                    <div class="social-icons">
                        <ul class="social">
                            <li><a href="#"><i></i></a> </li>
                            <li><a href="#"><i class="facebook"></i></a></li>
                            <li><a href="#"><i class="google"></i> </a></li>
                            <li><a href="#"><i class="linked"></i> </a></li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">
                <div class="clearfix"> </div>
                <p class="footer-class animated wow fadeInUp animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInUp;"> © 2020 Simba Records</p>
            </div>
        </div>
    </div>
    <!--footer-->
</template>